### ISSUE TITLE
Fabric 2.3.3 does not work

### ISSUE THREAD

**Issue by oldrich-s** [nhnent/tui.image-editor#39]
## Version
3.1.0

## Development Environment
latest Google Chrome

## Current Behavior
I get `canvasImage.setAngle is not a function` when using Fabric 2.3.3.

Fabric 1.6.7 works fine.

## Expected Behavior
It should probably work with Fabric 2.3.3 or the`Dependency` section should mention that `Fabric 2.3.3` is not supported.

**Comment by jinwoo-kim-nhn** [comment]
Currently, fabric 2.x.x does not guarantee normal operation.
Because the major version of fabricj has changed, there is a break change with the old version.
However, we will soon fix this issue for the continued improvement of the image editor.
thank you.
